#pragma once
typedef enum AsciiP {
    ASCIIPCtrl = 0x80,
    ASCIIPLshift,
    ASCIIPRshift,
    ASCIIPPtrsc,
    ASCIIPAlt,
    ASCIIPCapsLock,
    ASCIIPF1,
    ASCIIPF2,
    ASCIIPF3,
    ASCIIPF4,
    ASCIIPF5,
    ASCIIPF6,
    ASCIIPF7,
    ASCIIPF8,
    ASCIIPF9,
    ASCIIPF10,
    ASCIIPNumLock,
    ASCIIPScroll,
    ASCIIPHome,
    ASCIIPUp,
    ASCIIPPgup,
    ASCIIPLeft,
    ASCIIPCenter,
    ASCIIPRight,
    ASCIIPEnd,
    ASCIIPDown,
    ASCIIPPgdown,
    ASCIIPInsert,
    ASCIIPCBlack,
    ASCIIPCDBlue,
    ASCIIPCDGreen,
    ASCIIPCDCyan,
    ASCIIPCDRed,
    ASCIIPCDPurple,
    ASCIIPCBrown,
    ASCIIPCGray,
    ASCIIPCDGray,
    ASCIIPCBlue,
    ASCIIPCGreen,
    ASCIIPCCyan,
    ASCIIPCRed,
    ASCIIPCPurple,
    ASCIIPCYellow,
    ASCIIPCWhite,
    ASCIIPNextRaw,
} AsciiP;